language: python
python:
  - "2.7"
# command to install dependencies
script: "./install/install_kalliope.sh"
install: "pip install -r install/files/python_requirements.txt"
# command to run tests
script: pytest
